message_list =[
    [
                         ["Heartbeat",     "Out/In", 0,"quint32"],
                        [["Id (unique key)","utf8"],
                         ["Maximum schema number", "quint32"],   
                         ["version","utf8"],                  
                         ["revision","utf8"]]],
    [
                         ["Status","Out", 1, "quint32"],                      
                        [["Id (unique key)","utf8"],         
                         ["Dial Frequency (Hz)","quint64"],      
                         ["Mode","utf8"],                     
                         ["DX call","utf8"],                  
                         ["Report","utf8"],                   
                         ["Tx Mode","utf8"],                  
                         ["Tx Enabled","bool"],               
                         ["Transmitting","bool"],             
                         ["Decoding","bool"],                 
                         ["Rx DF","quint32"],                    
                         ["Tx DF","quint32"],                    
                         ["DE call","utf8"],                  
                         ["DE grid","utf8"],                  
                         ["DX grid","utf8"],                  
                         ["Tx Watchdog","bool"],              
                         ["Sub-mode","utf8"],                 
                         ["Fast mode","bool"],                
                         ["Special Operation Mode","quint8"],   
                         ["Frequency Tolerance","quint32"],      
                         ["T/R Period","quint32"],               
                         ["Configuration Name","utf8"],       
                         ["Tx Message","utf8"]]],
     [               
                         ["Decode","Out",2,"quint32"],                                     
                        [["Id (unique key)","utf8"],          
                         ["New","bool"],                      
                         ["Time","QTime"],                     
                         ["snr","qint32"],                      
                         ["Delta time (S)","float"],
                         ["Delta frequency (Hz)","quint32"],     
                         ["Mode","utf8"],                     
                         ["Message","utf8"],                  
                         ["Low confidence","bool"],           
                         ["Off air","bool"]]],
    [                   
                         ["Clear","Out/In",3,"quint32"],                                   
                        [["Id (unique key)","utf8"],          
                         ["Window","quint8"]]],
    [
                        [["Reply","In",4,"quint32"],                                       
                         ["Id (target unique key)","utf8"],   
                         ["Time","QTime"],                     
                         ["snr","qint32"],                      
                         ["Delta time (S)","float"],
                         ["Delta frequency (Hz)","quint32"],     
                         ["Mode","utf8"],                     
                         ["Message","utf8"],                  
                         ["Low confidence","bool"],           
                         ["Modifiers","quint8"]]],
    [                
                         ["QSO Logged","Out",5,"quint32"],                                 
                        [["Id (unique key)","utf8"],          
                         ["Date & Time Off","QDateTime"],          
                         ["DX call","utf8"],                  
                         ["DX grid","utf8"],                  
                         ["Tx frequency (Hz)","quint64"],        
                         ["Mode","utf8"],                     
                         ["Report sent","utf8"],              
                         ["Report received","utf8"],          
                         ["Tx power","utf8"],                 
                         ["Comments","utf8"],                 
                         ["Name","utf8"],                     
                         ["Date & Time On","QDateTime"],           
                         ["Operator call","utf8"],            
                         ["My call","utf8"],                  
                         ["My grid","utf8"],                  
                         ["Exchange sent","utf8"],            
                         ["Exchange received","utf8"],        
                         ["ADIF Propagation mode","utf8"]]],
    [    
                         ["Close","Out/In",6,"quint32"],                                   
                        [["Id (unique key)","utf8"]]],
    [          
                         ["Replay","In",7,"quint32"],                                      
                        [["Id (unique key)","utf8"]]],
    [          
                         ["Halt Tx","In",8,"quint32"],               
                        [["Id (unique key)","utf8"],          
                         ["Auto Tx Only","bool"]]],
    [             
                         ["Free Text","In",9,"quint32"],             
                        [["Id (unique key)","utf8"],          
                         ["Text","utf8"],                     
                         ["Send","bool"]]],
    [                     
                         ["WSPRDecode","Out",10,"quint32"],                                
                        [["Id (unique key)","utf8"],          
                         ["New","bool"],                      
                         ["Time","QTime"],                     
                         ["snr","qint32"],                      
                         ["Delta time (S)","float"],            
                         ["Frequency (Hz)","quint64"],           
                         ["Drift (Hz)","qint32"],               
                         ["Callsign","utf8"],                 
                         ["Grid","utf8"],                     
                         ["Power (dBm)","qint32"],              
                         ["Off air","bool"]]],
    [                  
                         ["Location","In",11,"quint32"],              
                        [["Id (unique key)","utf8"],
                         ["Location","utf8"]]],
    [                 
                         ["Logged ADIF","Out",12,"quint32"],                               
                        [["Id (unique key)","utf8"],          
                         ["ADIF text","utf8"]]],
    [                
                        [["Highlight Callsign","In",13,"quint32"],                         
                         ["Id (unique key)","utf8"],          
                         ["Callsign","utf8"],                 
                         ["Background Color","QColor"],         
                         ["Foreground Color","QColor"],         
                         ["Highlight last","bool"]]],
    [           
                         ["SwitchConfiguration","In",14,"quint32"],                        
                        [["Id (unique key)","utf8"],          
                         ["Configuration Name","utf8"]]],
    [       
                         ["Configure","In",15,"quint32"],                                  
                        [["Id (unique key)","utf8"],          
                         ["Mode","utf8"],                     
                         ["Frequency Tolerance","quint32"],      
                         ["Submode","utf8"],                  
                         ["Fast Mode","bool"],                
                         ["T/R Period","quint32"],               
                         ["Rx DF","quint32"],                    
                         ["DX Call","utf8"],                  
                         ["DX Grid","utf8"],                  
                         ["Generate Messages","bool"]]],
    [        
                         ["AnnotationInfo","In",16,"quint32"],                             
                        [["Id (unique key)","utf8"],          
                         ["DX Call","utf8"],                  
                         ["Sort Order Provided","bool"],      
                         ["Sort Order","quint32"]]]
    ]               
